//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_WebBanCayCanh_24DKTPM1A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
